twig:
    default_path: '%kernel.project_dir%/templates'
    globals: 
            logo_site: "/img/logo_site/"
            image_post: "/img/post/"
            exemple_post: "/img/standard_post/"
            profile_image: "/img/profile/"
            profile_standard: "/img/standard_profil/"
            fond_ecran: "/img/fond_ecran/"
            latestposts: '@App\Controller\Latestsposts\Latestsposts'
when@test:
    twig:
        strict_variables: true
